#+INCLUDE: ./main.setup
#+TITLE: How to contribute to Linux Commands
#+AUTHOR: Dongsoo Lee
#+EMAIL: dongsoolee8@gmail.com
#+DATE: 2018-02-26

* What is benefit of this project?

This project is made for documentation of all programs we use.
And all of documents are [[./STANDARD.org][standardized]] and have a clearfied sections.

Think about when you search for the information of Linux commands.
Your needs are just simple, but maybe you should be searching the internet for wasting times.
It will reduce your productivility and concentration.

This project focused on improving your productivility and preserving concentration.
You don't need to search for another web sites to get an information and don't have to confuse because of new sections or UI.
Only you need is familiar about one unified sections and UI!

And it is opensource, that means, all of docs are yours!

* Please share your knowledge

This project need your help to grow up.
Meaning of contributing on this project is that creating your own knowledge base and share your wisdom with community.
Your name will be recorded in what you contributed documents if you want, and people will thank of your contributions.

* What should I know to contribute?

First of all, you should know about *Org Mode*.
If you know about the Markdown syntax, It will be easier.
Or not, also easy to use and if you will be accustomed, you maybe love it.

It is builtin mode of Emacs, but it isn't that means only Emacs users can be use it.
You can use with your favorite editor, evenif text editor or github file editor.

Here is tutorial for Org Mode. Don't be afraid, I think, It might be the editor what you look for.
- [[https://orgmode.org/manual/index.html][Offical manual]]
- [[https://github.com/fniessen/refcard-org-mode][refcard-org-mode]]

Also see [[./org-mode.org][org-mode document]]

* Contributing with your native language

You shouldn't have to use only English. It's up to you.
In fact, we need more contribution of your native language.

This project deploys the contents automatically splited by languages.
Only contributing one file, It will be split 5 files with English, Spanish, Korean, Chinese and Japanese(currently support).

And here is the distributed contents currently working.
- [[http://linux-command.org/en][English]]
- [[http://linux-command.org/es][Español]]
- [[http://linux-command.org/ko][한국어]]
- [[http://linux-command.org/zh][中文]]
- [[http://linux-command.org/ja][日本語]]

You want to new language? It's a piece of cake.
Just add lang code with newline in the [[./.supportLanguages][supportLanguages]] file.

You can add your language simply using "#+LANG_XX:" keyword.
Also section type, block type or emphasis type are currently supported.
Here is detail usage of the multilingual keywords on [[https://github.com/mrlee23/org-multilingual][here]].

* Writing document

All of documents sections are standardized depending on [[./STANDARD.org][STANDARD template]].
Only the section which exists in the standard file, should be used for keeping the unity.
And some sections have static form for more clearfy the meaning. (eg. Syntax - only use the code block to be shown quick usage)

* Commit rules

** prefixes
- Macro : Relate org macros.
- Elisp : Relate linux-commands.el
- En, Es, Ko, Zh, Ja, ... : Relate language with org document of Linux Commands.
- CI/CD : Modified .travis.yml, Makefile and linux-commands-pages.el
- Pages : Modifications of assets.

* Macros

** Inline
- REDIRECT(string location)
- VERSION(string version)
- LATEST_VERSION(string version)
- BUILTIN
- INCLUDE_PROGRESS
- INCLUDE_DOCS
- META

*** Related image
- IMAGE(string path, string name, string classes)
- IMAGE_CENTER(string path, string name, string classes)
- IMAGE_RIGHT(string path, string name, string classes)
- IMAGE_MAIN(string name)
- IMAGE_LINK(string path, string name, string classes)
- IMAGE_LINK_CENTER(string path, string name, string classes)
- IMAGE_LINK_RIGHT(string path, string name, string classes)
