#+INCLUDE: ./main.setup
#+TITLE: finger
#+AUTHOR: Dongsoo Lee
#+EMAIL: dongsoolee8@gmail.com
#+DATE: 2018-02-22

* Overview
  :PROPERTIES: 
  :CUSTOM_ID: overview
  :LANG: en
  :END:      

 Display user's information.

* How to Install
  :PROPERTIES: 
  :CUSTOM_ID: how-to-install
  :LANG: en
  :END:      

# ** Prerequisites
#    :PROPERTIES: 
#    :CUSTOM_ID: prerequisites
#    :LANG_EN:  Prerequisites
#    :LANG_ES:  Requisitos previos
#    :LANG_KO:  필요 사항
#    :LANG_ZH:  先决条件
#    :LANG_JA:  前準備
#    :END:      

** Install
  :PROPERTIES: 
  :CUSTOM_ID: install
  :LANG: en
  :END:      

#+BEGIN_SRC sh
$ sudo apt-get install finger
#+END_SRC

# ** Installed Packages
#    :PROPERTIES: 
#    :CUSTOM_ID: packages
#    :LANG_EN:  Installed Packages
#    :LANG_ES:  Paquetes instalados
#    :LANG_KO:  설치된 패키지
#    :LANG_ZH:  安装的软件包
#    :LANG_JA:  インストールされたパッケージ
#    :END:      

# ** Check
#    :PROPERTIES: 
#    :CUSTOM_ID: check
#    :LANG_EN:  Check
#    :LANG_ES:  Comprobar
#    :LANG_KO:  확인
#    :LANG_ZH:  检查
#    :LANG_JA:  チェック
#    :END:      

* Usage
  :PROPERTIES: 
  :CUSTOM_ID: usage
  :LANG: en
  :END:      

** Syntax
   :PROPERTIES: 
   :CUSTOM_ID: syntax
   :LANG: en
   :END:      


#+BEGIN_SRC sh
finger [-lmsp] [user ...] [user@host ...]
#+END_SRC

** Configuration
   :PROPERTIES: 
   :CUSTOM_ID: configuration
   :LANG: en
   :END:      

- {{{file(~/.nofinger)}}} :
 If finger finds this file in a user's home directory, it will, for finger requests originating outside the local host, firmly deny the existence of that
 user.  For this to work, the finger program, as started by fingerd(8), must be able to see the .nofinger file. This generally means that the home direc‐
 tory containing the file must have the other-users-execute bit set (o+x). See chmod(1).  If you use this feature for privacy, please test it with ``finger
 @localhost'' before relying on it, just in case.
- {{{file(~/.plan)}}}
- {{{file(~/.project)}}}
- {{{file(~/.pgpkey)}}} :
 These files are printed as part of a long-format request. The .plan file may be arbitrarily long.

** Options
   :PROPERTIES: 
   :CUSTOM_ID: options
   :LANG: en
   :END:      

- {{{option(-s)}}} :
 Finger displays the user's login name, real name, terminal name and write status (as a ``*'' after the terminal name if write permission is denied), idle time, login time, office location and office phone number.
  - Login time is displayed as month, day, hours and minutes, unless more than six months ago, in which case the year is displayed rather than the hours and minutes.
  - Unknown devices as well as nonexistent idle and login times are displayed as single asterisks.
- {{{option(-l)}}} :
 Produces a multi-line format displaying all of the information described for the -s option as well as the user's home directory, home phone number, login shell, mail status, and the contents of the files “.plan”, “.project”, “.pgpkey” and “.forward” from the user's home directory.
  - Phone numbers specified as eleven digits are printed as ``+N-NNN-NNN-NNNN''.  Numbers specified as ten or seven digits are printed as the appropriate subset of that string.  Numbers specified as five digits are printed as ``xN-NNNN''.  Numbers specified as four digits are printed as ``xNNNN''.
  - If write permission is denied to the device, the phrase ``(messages off)'' is appended to the line containing the device name.  One entry per user is displayed with the -l option; if a user is logged on multiple times, terminal information is repeated once per login.
  - Mail status is shown as ``No Mail.'' if there is no mail at all, ``Mail last read DDD MMM ## HH:MM YYYY (TZ)'' if the person has looked at their mailbox since new mail arriving, or ``New mail received ...'', ``  Unread since ...'' if they have new mail.
- {{{option(-p)}}} :
 Prevents the -l option of finger from displaying the contents of the “.plan”, “.project” and “.pgpkey” files.
- {{{option(-m)}}} :
 Prevent matching of user names.  User is usually a login name; however, matching will also be done on the users' real names, unless the -m option is supplied.  All name matching performed by finger is case insensitive.

# ** Examples
#    :PROPERTIES: 
#    :CUSTOM_ID: examples
#    :LANG_EN:  Examples
#    :LANG_ES:  Ejemplos
#    :LANG_KO:  사용 예
#    :LANG_ZH:  例子
#    :LANG_JA:  例
#    :END:      

* See also
  :PROPERTIES: 
  :CUSTOM_ID: seealso
  :LANG: en
  :END:      

- {{{link(chfn)}}}
- {{{link(passwd)}}}
- {{{link(w)}}}
- {{{link(who)}}}

# * References
#   :PROPERTIES: 
#   :CUSTOM_ID: references
#   :LANG_EN:  References
#   :LANG_ES:  Referencias
#   :LANG_KO:  참고자료
#   :LANG_ZH:  参考
#   :LANG_JA:  参考
#   :END:      
