#+INCLUDE: ./main.setup
#+TITLE: hcitool
#+AUTHOR: Dongsoo Lee
#+EMAIL: dongsoolee8@gmail.com
#+DATE: 2018-02-20

* Overview
  :PROPERTIES: 
  :CUSTOM_ID: overview
  :LANG: en
  :END:      

Configure Bluetooth connections

** Introduction
  :PROPERTIES: 
  :CUSTOM_ID: introduction
  :LANG: en
  :END:    

hcitool is used to configure Bluetooth connections and send some special command to Bluetooth devices.
If no command is given, or if the option -h is used, hcitool prints some usage information and exits.

# * How to Install
#   :PROPERTIES: 
#   :CUSTOM_ID: how-to-install
#   :LANG_EN:  How to Install
#   :LANG_ES:  Cómo instalar
#   :LANG_KO:  설치 방법
#   :LANG_ZH:  如何安装
#   :LANG_JA:  インストール方法
#   :END:      

# ** Prerequisites
#    :PROPERTIES: 
#    :CUSTOM_ID: prerequisites
#    :LANG_EN:  Prerequisites
#    :LANG_ES:  Requisitos previos
#    :LANG_KO:  필요 사항
#    :LANG_ZH:  先决条件
#    :LANG_JA:  前準備
#    :END:      

# ** Install
#   :PROPERTIES: 
#   :CUSTOM_ID: install
#   :LANG_EN:  Install
#   :LANG_ES:  Instalar
#   :LANG_KO:  설치
#   :LANG_ZH:  安装
#   :LANG_JA:  インストール
#   :END:      

# ** Installed Packages
#    :PROPERTIES: 
#    :CUSTOM_ID: packages
#    :LANG_EN:  Installed Packages
#    :LANG_ES:  Paquetes instalados
#    :LANG_KO:  설치된 패키지
#    :LANG_ZH:  安装的软件包
#    :LANG_JA:  インストールされたパッケージ
#    :END:      

# ** Check
#    :PROPERTIES: 
#    :CUSTOM_ID: check
#    :LANG_EN:  Check
#    :LANG_ES:  Comprobar
#    :LANG_KO:  확인
#    :LANG_ZH:  检查
#    :LANG_JA:  チェック
#    :END:      

* Usage
  :PROPERTIES: 
  :CUSTOM_ID: usage
  :LANG: en
  :END:      

** Syntax
   :PROPERTIES: 
   :CUSTOM_ID: syntax
   :LANG: en
   :END:      

#+BEGIN_SRC sh
hcitool [-h]
hcitool [-i <hciX>] [command [command parameters]]
#+END_SRC

# ** Configuration
#    :PROPERTIES: 
#    :CUSTOM_ID: configuration
#    :LANG_EN:  Configuration
#    :LANG_ES:  Configuración
#    :LANG_KO:  설정
#    :LANG_ZH:  组态
#    :LANG_JA:  設定
#    :END:      

** Options
   :PROPERTIES: 
   :CUSTOM_ID: options
   :LANG: en
   :END:      

- {{{option(-h)}}} :
- {{{option(-i)}}} {{{argument(<hciX>)}}} :

** Commands
   :PROPERTIES: 
   :CUSTOM_ID: commands
   :LANG: en
   :END:      

*** dev
Display local devices
*** inq
Inquire remote devices. For each discovered device, Bluetooth device address, clock offset and class are printed.
*** scan
Inquire remote devices. For each discovered device, device name are printed.
*** name <bdaddr>

**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
name <bdaddr>
#+END_SRC


Print device name of remote device with Bluetooth address bdaddr.
*** info <bdaddr>
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
info <bdaddr>
#+END_SRC

 Print device name, version and supported features of remote device with Bluetooth address bdaddr.
*** spinq 

Start periodic inquiry process. No inquiry results are printed.
*** epinq
Exit periodic inquiry process.
*** cmd
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
cmd <ogf> <ocf> [parameters]
#+END_SRC

 Submit an arbitrary HCI command to local device. ogf, ocf and parameters are hexadecimal bytes.
*** con
Display active baseband connections
*** cc
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
cc [--role=m|s] [--pkt-type=<ptype>] <bdaddr>
#+END_SRC

 Create baseband connection to remote device with Bluetooth address bdaddr. Option --pkt-type specifies a list of allowed packet types. <ptype> is a comma-sepa‐
 rated list of packet types, where the possible packet types are DM1, DM3, DM5, DH1, DH3, DH5, HV1, HV2, HV3. Default is to allow all packet types. Option --role
 can have value m (do not allow role switch, stay master) or s (allow role switch, become slave if the peer asks to become master). Default is m.
*** dc
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
dc <bdaddr> [reason]
#+END_SRC

 Delete baseband connection from remote device with Bluetooth address bdaddr. The reason can be one of the Bluetooth HCI error codes. Default is 19 for user ended
 connections. The value must be given in decimal.
*** sr
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
sr <bdaddr> <role>
#+END_SRC

 Switch role for the baseband connection from the remote device to master or slave.
*** cpt
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
cpt <bdaddr> <packet types>
#+END_SRC

 Change packet types for baseband connection to device with Bluetooth address bdaddr. packet types is a comma-separated list of packet types, where the possible
 packet types are DM1, DM3, DM5, DH1, DH3, DH5, HV1, HV2, HV3.
*** rssi
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
rssi <bdaddr>
#+END_SRC

 Display received signal strength information for the connection to the device with Bluetooth address bdaddr.
*** lq
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lq <bdaddr>
#+END_SRC

 Display link quality for the connection to the device with Bluetooth address bdaddr.
*** tpl
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
tpl <bdaddr> [type]
#+END_SRC

 Display transmit power level for the connection to the device with Bluetooth address bdaddr. The type can be 0 for the current transmit power level (which is
 default) or 1 for the maximum transmit power level.
*** afh
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
afh <bdaddr>
#+END_SRC

 Display AFH channel map for the connection to the device with Bluetooth address bdaddr.
*** lp
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lp <bdaddr> [value]
#+END_SRC

 With no value, displays link policy settings for the connection to the device with Bluetooth address bdaddr. If value is given, sets the link policy settings for
 that connection to value. Possible values are RSWITCH, HOLD, SNIFF and PARK.
*** lst
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lst <bdaddr> [value]
#+END_SRC

 With no value, displays link supervision timeout for the connection to the device with Bluetooth address bdaddr. If value is given, sets the link supervision
 timeout for that connection to value slots, or to infinite if value is 0.
*** auth
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
auth <bdaddr>
#+END_SRC

 Request authentication for the device with Bluetooth address bdaddr.
*** enc
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
enc <bdaddr> [encrypt enable]
#+END_SRC

 Enable or disable the encryption for the device with Bluetooth address bdaddr.
*** key
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
key <bdaddr>
#+END_SRC

 Change the connection link key for the device with Bluetooth address bdaddr.
*** clkoff
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
clkoff <bdaddr>
#+END_SRC

 Read the clock offset for the device with Bluetooth address bdaddr.
*** clock
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
clock [bdaddr] [which clock]
#+END_SRC

 Read the clock for the device with Bluetooth address bdaddr. The clock can be 0 for the local clock or 1 for the piconet clock (which is default).
*** lescan
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lescan [--privacy] [--passive] [--whitelist] [--discovery=g|l] [--duplicates]
#+END_SRC

 Start LE scan
*** leinfo
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
leinfo [--static] [--random] <bdaddr>
#+END_SRC

 Get LE remote information
*** lewladd
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lewladd [--random] <bdaddr>
#+END_SRC

 Add device to LE White List
*** lewlrm
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lewlrm <bdaddr>
#+END_SRC

 Remove device from LE White List
*** lewlsz
Read size of LE White List
*** lewlclr
 Clear LE White List
*** lerladd
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lerladd [--local irk] [--peer irk] [--random] <bdaddr>
#+END_SRC

 Add device to LE Resolving List
*** lerlrm
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lerlrm <bdaddr>
#+END_SRC

 Remove device from LE Resolving List
*** lerlclr
 Clear LE Resolving List
*** lerlsz
Read size of LE Resolving List
*** lerlon
Enable LE Address Resolution
*** lerloff
 Disable LE Address Resolution
*** lecc
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lecc [--static] [--random] <bdaddr> | [--whitelist]
#+END_SRC

 Create a LE Connection
*** ledc
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
ledc <handle> [reason]
#+END_SRC

 Disconnect a LE Connection
*** lecup
**** Syntax
   	 :PROPERTIES: 
   	 :CUSTOM_ID: syntax
   	 :LANG: en
   	 :END:      

#+BEGIN_SRC sh
lecup <handle> <min> <max> <latency> <timeout>
#+END_SRC

 LE Connection Update

# ** Examples
#    :PROPERTIES: 
#    :CUSTOM_ID: examples
#    :LANG_EN:  Examples
#    :LANG_ES:  Ejemplos
#    :LANG_KO:  사용 예
#    :LANG_ZH:  例子
#    :LANG_JA:  例
#    :END:      

# * See also
#   :PROPERTIES: 
#   :CUSTOM_ID: seealso
#   :LANG_EN:  See also
#   :LANG_ES:  Ver también
#   :LANG_KO:  관련 항목
#   :LANG_ZH:  相关主题
#   :LANG_JA:  関連項目
#   :END:      

# * References
#   :PROPERTIES: 
#   :CUSTOM_ID: references
#   :LANG_EN:  References
#   :LANG_ES:  Referencias
#   :LANG_KO:  참고자료
#   :LANG_ZH:  参考
#   :LANG_JA:  参考
#   :END:      
